if: (type = push AND branch = master) OR type = pull_request

os:
  - linux
dist: xenial

language: go

go: "1.14.1"
go_import_path: github.com/Shopify/ghostferry

services:
  - docker

stages:
  - Test
  - name: Documentation
    if: type = push AND branch = master
  - name: Package
    if: type = push AND branch = master

env:
  global:
    - CI=true
    - DOCKER_COMPOSE_VERSION=1.21.2

jobs:
  include:
    - stage: Test
      name: Go Tests
      script: make test-go
    - script: make test-ruby
      name: Ruby Tests
    - stage: Documentation
      script: .travisci/build-docs.sh
      deploy:
        - provider: pages
          strategy: git
          token: "$GITHUB_TOKEN"
          keep_history: true
          local_dir: docs/build/ghostferry-pages
          skip_cleanup: true
    - stage: Package
      script:
        - .travisci/build-docs.sh
        - .travisci/build-debs.sh
        - .travisci/deploy-packagecloud.sh
      deploy:
        - provider: releases
          token: "$GITHUB_TOKEN"
          file_glob: true
          file: build/ghostferry-*.deb
          skip_cleanup: true
          on:
            tags: true

before_script:
  - ulimit -n 16384

install:
  # Installing Docker Compose
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

  # Installing and Starting MySQL
  - .travisci/start-mysql.sh
