name: ghostferry

env:
  MYSQL_VERSION: "8.0"

up:
  - packages:
      - mysql-client@5.7
  - ruby
  - bundler
  - go:
      version: "1.21.3"
  - podman
  - custom:
      name: Go Dependencies
      met?: go mod download
      meet: echo 'go mod failed to download dependencies'; false
  - custom:
      name: MySQL
      met?: podman-compose -f docker-compose_8.0.yml up -d mysql-1 mysql-2
      meet: echo 'mysql failed to start'; false
      down: podman-compose -f docker-compose_8.0.yml stop mysql-1 mysql-2

commands:
  test:
    desc: Run all the tests.
    run: make test
  test-go:
    desc: Run the golang test suite.
    run: make test-go
  test-ruby:
    desc: Run the ruby test suite.
    run: make test-ruby
