name: ghostferry

up:
  - homebrew:
    - mysql
  - ruby: 2.5.1
  - bundler
  - go:
      version: 1.12.7
      modules: true
  - custom:
      name: Docker for Mac
      met?: test -e /Applications/Docker.app
      meet: echo "Docker not found. Install from https://docs.docker.com/docker-for-mac/"; false
  - custom:
      name: Go Dependencies
      met?: go mod verify
      meet: echo 'go mod failed to verify dependencies'; false
  - custom:
      name: MySQL
      met?: docker-compose up -d mysql-1 mysql-2
      meet: echo 'mysql failed to start'; false
      down: docker-compose stop mysql-1 mysql-2

env:
  GOFLAGS: '-mod=vendor'

commands:
  test:
    desc: Run the test suite.
    run: make test
